DROP TABLE STUDENT;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
DeptID NUMBER PRIMARY KEY,
DeptName VARCHAR2(50)
);

CREATE TABLE STUDENT (
SID NUMBER PRIMARY KEY,
Name VARCHAR2(50),
DeptID NUMBER REFERENCES DEPARTMENT(DeptID)
);

INSERT INTO DEPARTMENT VALUES (10, 'Computer Science');
INSERT INTO DEPARTMENT VALUES (20, 'Mathematics');
INSERT INTO DEPARTMENT VALUES (30, 'Physics');
INSERT INTO DEPARTMENT VALUES (40, 'Chemistry');

INSERT INTO STUDENT VALUES (1, 'Alice', 10);
INSERT INTO STUDENT VALUES (2, 'Bob', 20);
INSERT INTO STUDENT VALUES (3, 'Charlie', NULL);
INSERT INTO STUDENT VALUES (4, 'David', 10);
INSERT INTO STUDENT VALUES (5, 'Eva', 30);

SELECT * FROM STUDENT WHERE DeptID = 10;

SELECT Name FROM STUDENT;

SELECT * FROM STUDENT, DEPARTMENT;

SELECT S.SID, S.Name, D.DeptName
FROM STUDENT S
LEFT OUTER JOIN DEPARTMENT D
ON S.DeptID = D.DeptID;

SELECT S.SID, S.Name, D.DeptName
FROM STUDENT S
RIGHT OUTER JOIN DEPARTMENT D
ON S.DeptID = D.DeptID;

SELECT S.SID, S.Name, D.DeptName
FROM STUDENT S
FULL OUTER JOIN DEPARTMENT D
ON S.DeptID = D.DeptID;
